### ISSUE TITLE
Dangerous nil unwrapping may happen

### ISSUE THREAD

**Issue by fadi-botros** [ahmedk92/WKJSEvalPromise#1]
https://github.com/ahmedk92/WKJSEvalPromise/blob/32a1d349d5df8320b08be07eab8ea41b5af0846d/WKJSEvalPromise/WKJSEvalPromise.swift#L16

This may cause unwrapping of nil (if the object is released from memory), either use `weak` and `?` to be safe,  or `unowned` (not-recommended) for more performance with almost the same effect as using `!` (a crash)

**Comment by ahmedk92** [comment]
True. However, taking the optional route, I'm not sure what to do if `guard let` fails. Any ideas?

**Comment by fadi-botros** [comment]
https://github.com/ahmedk92/WKJSEvalPromise/blob/32a1d349d5df8320b08be07eab8ea41b5af0846d/WKJSEvalPromise/WKJSEvalPromise.swift#L25

We could replace this factory method with a constructor (an initializer). And remove the empty parameter constructor (initializer, which is defined at line 23), so that the JSEvaluator wouldn't be optional

**Comment by ahmedk92** [comment]
> so that the JSEvaluator wouldn't be optional

This implies keeping a strong reference to the `JSEvaluator `, which I think we shouldn't do. Let the `JSEvaluator` (which is most likely a `WKWebView`) deallocate when appropriate.

**Comment by ahmedk92** [comment]
I'm thinking letting it be optional and do nothing if `guard let` fails; that simulates a cancelation, albeit without reporting that cancelation.

**Comment by fadi-botros** [comment]
If you want to make it "weak", consider the `unowned` here, but note it is unsafe

**Comment by fadi-botros** [comment]
Also, try, to make it like Scala's and JS's promises, which also have something like `onError` (called `catch`), so if the promises fails for any reason, (including a `nil` JSEvalutor in your case), should be called.

Please note that there is a lot of less code if we separated the failure callback from success callback.
(This decreases a lot of `if let err = error`)

**Comment by ahmedk92** [comment]
Both issues are fixed now. Thank you Fadi!
